# Generated by Django 5.2.12 on 2026-03-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaminApp_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
